services:
  - type: web
    name: medical-ai-chatbot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false